"""add Item model

Revision ID: 01b3b785ce4d
Revises: 662789fe1d36
Create Date: 2023-09-21 16:39:43.522701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "01b3b785ce4d"
down_revision = "662789fe1d36"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("registered_on", sa.DateTime(), nullable=True),
        sa.Column("registered_by", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["registered_by"],
            ["site_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("price", sa.Float(precision=2), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("items")
    op.drop_table("stores")
    # ### end Alembic commands ###
