"""add BlacklistedToken model

Revision ID: 662789fe1d36
Revises: 31ab0b097bad
Create Date: 2023-09-21 00:18:51.128600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "662789fe1d36"
down_revision = "31ab0b097bad"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "token_blacklist",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("token", sa.String(length=500), nullable=False),
        sa.Column("blacklisted_on", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("token_blacklist")
    # ### end Alembic commands ###
